---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-dep
  labels:
    type: java-app
spec:
  replicas: 2
  selector:
   matchLabels:
    type: java-app
  template:
    metadata:
      name: java-dep
      labels:
        type: java-app
    spec:
     containers:
       - name: java-app
         image: 852068596012.dkr.ecr.us-east-1.amazonaws.com/san-test-ecr
         resources:
          requests:
            cpu: 200m
            memory: 500Mi